import snapshot from "@/data/curriculum.json";
import type { Curriculum } from "./curriculum-types";

/**
 * The whole plan (16 weeks, 64 days, ~900 items). It ships with the app as a JSON snapshot generated by
 * `npm run data:build`, so the site needs no database or server to run. The Postgres schema in src/db is kept
 * for when editing moves online (docs/design.md).
 */
export async function getCurriculum(): Promise<Curriculum> {
  return snapshot as Curriculum;
}
